title: Maila Aziza
email: mailaazizaaiyub@gmail.com
description: Saya merupakan mahasiswa semester 2 prodi Teknik Informatika di Politeknik Negeri Lhokseumawe. Saya lahir di Lhokseumawe pada 17 Mei 2006.

url: 'https://melax64.github.io'

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag